export const SCREENS = {
  // Auth Screens
  SPLASH: "SPLASH",
  ONBOARDING: "OnBoarding",
  LOGIN: "Login",
  REGISTER: "REGISTER",
  NOTIFICATION: 'NOTIFICATION',
  //App Screens
  HOME: "HOME",
  BOOKING: "BOOKINGS",
  TRACK: "TRACK",
  REWARDS: "REWARDS",
  DRAWERNAVIGATION: "DRAWERNAVIGATION",
  VERIFYOTP: "VERIFYOTP",
  BOTTOMNAVIGATION: "BOTTOMNAVIGATION",
  TYPEOFUSERS: 'TYPEOFUSERS',
  APPNAVIGATION: 'APPNAVIGATION',
  AUTHNAVIGATION: 'AUTHNAVIGATION',
  EDITPROFILE: "EDITPROFILE",
  VIEWDOCUMENTS: "VIEWDOCUMENTS",
  //side menu
  PROFILE: 'PROFILE',
  BOOKINGDETAILS: 'BOOKING DETAILS',
  TRACKYOURRIDES: 'TRACKYOURRIDES',
  DOCUMENTS: 'DOCUMENTS',
  PRIVACYPOLICIY: 'PRIVACYPOLICIY',
  SUPPORT: 'SUPPORT',
  LOGOUT: 'LOGOUT',
  BOOKINGHISTORY: 'BOOKING HISTORY',
  RECEIVERPLACE: "RECEIVER PLACE",
  APPDRAWERSTACK: "APP DRAWER STACK",
  APPBOTTOMSTACK: "APP BOTTOM STACK",
  /* -----------------Owner flow ------------------- */
  TRACKDRIVERROUTE: 'TRACKDRIVERROUTE',
  MANAGEDRIVER: 'MANAGEDRIVER',
  MANAGETRUCK: 'MANAGETRUCK',
  ASSIGNEDTRUCKANDDRIIVER: 'ASSIGNEDTRUCKANDDRIIVER'

};
