import {iconpathurl} from '../assets/iconpath';
export const strings = {
  login: 'Login',
  emailPhoneNumber: 'Phone number',
  enterHere: 'Please enter here',
  enterHereDot: 'Enter here...',
  verifyWithOtp: 'Verify with OTP',
  newToVelo: 'New to Velo?',
  registerWithUs: 'Register with us',
  typeOfUser: 'Please choose for \n the login',
  proceed: 'Proceed',
  owner: 'Owner',
  driver: 'Driver',
  success: 'Success',
  onGoing: 'Ongoing',
  scheduled: 'Scheduled',
  newBooking: 'New Booking',
  completed: 'Completed',
  cancelled: 'Cancelled',
  yetToConfirm: 'yet To Confirm',
  privacyPolicy: 'Privacy Policy',
  vehicleNumber: 'vehicle Number',
  vehicleType: 'vehicleType',
  firstName: 'First Name',
  lastName: 'Last Name',
  //onBoarding
  choice:
    'Kindly choose your appropriate role in order to continue exploring Velo.',
  /*-------------Driver Flow ------------------*/
  driverOnboadringTxt1: 'QUICK RIDES FOR YOU',
  driverOnboadringTxt2: 'TRACK YOUR ROUTE',
  driverOnboadringTxt3: 'SCHEDULE YOUR DRIVE',
  driverOnboadringsubTxt1:
    'Optimize your journey with swift and reliable transportation options.',
  driverOnboadringsubTxt2:
    'Stay informed every step of the way with real-time route tracking.',
  driverOnboadringsubTxt3:
    'Take control of your schedule by planning your drives in advance.',
  /* --------------owner flow --------------- */
  ownerOnboardingTitle: "Owner's Tracking Hub",
  ownerOnboardingTitle1: 'TRACK DRIVER TRIPS',
  ownerOnboardingTitle2: 'Assign Drivers',
  ownerOnboardingTxt1:
    "Take charge of your fleet's movements with our comprehensive tracking hub.",
  ownerOnboardingTxt2:
    'Stay updated on trip progress and ensure timely deliveries.',
  ownerOnboardingTxt3:
    'Optimize efficiency by assigning tasks swiftly and effectively',
  //register
  register: 'Register',
  name: 'Name',
  phno: 'Phone number',
  emailId: 'Email Id',
  termsAndCondition:
    'By registering you’ll be accepting the terms and condition of velo and their privacy policy.',
  whatsAppNotify: 'Enable WhatsApp notification from Velo',
  registerSuccess: `Registration \n successful`,
  registerSuccessTxt: `You have successfully registered with \n us. Please login with the credentials \n that are registered with us!`,

  //verifyOTP
  verifyOTP: 'Verify OTP',
  verify: 'Verify',
  otpDescription:
    'Please enter the OTP that has been shared on the phone number',
  //notification
  notifyHeader: 'Can We Notify You?',
  dummyTxt: 'Lorem Ipsum is simply dummy text of the printing and typesetting.',
  otherTime: 'No, Other Time',
  allow: 'Allow',
  // Booking
  quickBooking: 'Quick Booking',
  distance: 'Distance',
  truckNumber: 'Truck Number',
  truckModal: 'Truck Model',

  //side Menu
  menu: 'Menus',
  profile: 'Profile',
  bookingDetails: 'Bookings',
  bookingDetail: 'Booking Details',
  trackYourRide: 'Track your Route',
  documents: 'Documents',
  invoice: 'Invoice',
  referaFriend: 'Refer a friend',
  privacyPolicy: 'Privacy policy',
  support: 'Support',
  logout: 'Logout',
  home: 'Home',
  /* -------------- oowner flow -------------- */

  trackDriver: 'Track Driver Routes',
  manageDriver: 'Manage Driver',
  manageTruck: 'Manage Truck',
  assignTruckAndDriver: 'Assigned Truck / Driver',

  date: 'Date',
  pickupTime: 'Pickup Time ',
  loadType: 'Load Type',
  requiredVehicle: 'Required Vehicle',
  //home
  receiverNumber: 'Receiver Number',
  bookedBy: 'Booked By',
  receiver: 'Receiver',
  startDate: 'Start Time',
  eta: 'ETA',
  logginAs: 'Want to Login as',
  pickUpAddress: 'Pick Up Address',
  dropOfAddress: 'Drop Off Address',
  scheduled: 'Scheduled',
  running: 'Running',
  completed: 'Completed',
  location: 'Location',
  startRoute: 'Start Route',
  deliveryBtn: 'Start route to delivery',
  deliveredTime: 'Delivered Time',
  rating: 'Rating',
  upcomming: 'Upcoming',
  upcommingTrips: 'Upcoming Trip',
  current: 'Current',
  currentTrip: 'Current Trip',
  past: 'Past',
  pastTrip: 'Past Trip',
  viewRoute: 'View Route',
  addBreak: 'Add Break',
  //trackyourRoute
  timeDuration: 'Time Duration',
  //logout
  areYouSure: 'Are you sure you want to logout from velo?',
  logoutOfVelo: 'Logout of Velo',
  yes: 'Yes',
  no: 'No',
  /* -------------owner Flow ---------------*/
  viewDetails: 'View Details',
  contactNumber: 'Contact Number',
  contactNo: 'contact No',
  add: 'Add',

  // receiverPlace
  congarts: 'Congrats, You have reached to User’s place!',
  dropCongrats: 'Congrats, You have reached to Receiver’s place!',
  pickupyourDelivery: 'Pickup your Delivery',
  size: 'Size',
  uploadImage: 'Upload Image',
  uploadLoading: 'Upload Loading',
  weight: 'Weight Bridge Receipt',
  beforeWeight: 'Weighbridge before loading',
  afterWeight: 'Weighbridge after loading',
  otherDocument: 'Other documents',
  callReceiver: 'Call Receiver',
  close: 'Close',
  loadedTruck: 'Loaded Truck',
  unLoading: 'Upload Un-Loading',
  completeTrip: 'Complete Trip',
  dropOffDelivery: 'Drop off Delivery',
  DropTime: 'Dropoff Time',
  tripStatus: 'Trip Status',
  paymentStatus: 'Payment Status',
  // add Break
  addBreakHalt: 'Add Break / Halt',
  typeOfBreak: 'Choose type of break',
  typeReason: 'Type reason',
  endTimer: 'End Timer',
  startTimer: 'Start Timer',

  //profile information
  personalInfo: 'Personal Information',
  email: 'Email',
  phnNo: 'Phone No',
  alternatePhnNumber: 'Alternate Phone No.',
  city: 'City',
  country: 'Country',
  zipCode: 'Zip Code',
  myNotificationSettings: 'My Notification Settings',
  editDetails: 'Edit Details',
  deleteAccount: 'Delete Account',
  address: 'Address',
  ownerName: 'Owner Name',
  ownerPhno: 'Owner Phone No.',

  //edit profile
  editProfile: 'Edit Profile',
  enterName: 'Enter Name',
  enterPhoneNumber: 'Enter Phone Number',
  enterEmailID: 'Enter Email ID',
  enterAddress: 'Enter Address',
  enterCity: 'Enter City',
  enterZipCode: 'Enter Zip Code',
  enterCountry: 'Enter Country',
  save: 'Save',
  gallery: 'gallery',
  camera: 'Camera',
  selectType: 'Select Type',
  nodata: 'No Data Found',
  documentsUpload: 'Documents Upload',
  drivingLicense: 'Driving License',
  vehicleInsurance: 'Vehicle Insurance',
  browse: 'Browse',
  yourRooms: 'Your Rooms',
  addTxt: '+ Add',
  addDevTxt: '+ Add Devices',
  welcomeHome: 'Welcome to Home',
};

export const errorMsg = {
  emailError: 'Enter Email / Phone number',
  validEmailPhno: 'Enter a Valid Email Or Phone Number',
  userName: 'Please Enter Name',
  phoneNumber: 'Please Enter Phone Number',
  emailIdErr: 'Please Enter Email Id',
  validPhno: 'Enter a Valid 10 Digits Of Phone Number',
  validUserName: 'Enter a Valid Name',
  validEmail: ' Enter a Valid Email Id',
  userError: 'Select the user',
  typeOfBreak: 'Select the type of Break',
  typeOfReason: 'Please Enter Type of Reason',
};
